#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Protect master from accidental commits.
echo -e "===\n>> Checking branch name"
branchName=$(git branch | grep '*' | sed 's/* //')
echo $branchName
if [ $branchName == 'main' ]
then
  echo -e "\n🚫 Commit directly to master branch is not allowed!\n" && exit 1
fi

if [ $branchName == 'develop' ]
then
  echo -e "\n🚫 Cannot push to remote develop branch, please create your own branch and use PR."
fi

echo -e ">> Finish checking branch name.\n==="
echo -e ">> Pushing to $branchName\n==="

npm run lint
npm run test